### ISSUE TITLE
query-string not compiler by babel

### ISSUE THREAD

**Issue by shouhou** [sindresorhus/query-string#209] opened 2019-09-09 03:02 UTC
[BUG][BUG][BUG]

Our system crash when user use the IOS9 system due to the "const" syntax error.

const strictUriEncode = __webpack_require__(219);
const decodeComponent = __webpack_require__(220);
const splitOnFirst = __webpack_require__(221);

`module: {
    rules: [
        {
            test: /\.js[x]?$/,
            use: ['babel-loader'],
            exclude: /node_modules/
        }
    ]
}
`

Please upgrade ,and use babel to compiler the es6 syntax。

**Comment by sindresorhus** [comment] 2019-09-09 05:41
Duplicate of #208

**Closed by sindresorhus** 2019-09-09 05:41 UTC
