### ISSUE TITLE
publish pre-compiled package

### ISSUE THREAD

**Issue by zthornto** [sindresorhus/query-string#132] opened 2018-03-15 19:58 UTC
I'm hoping to use this package as part of a create-react-app build, but it's running into issues when creating an optimized production build.

Details outlined here: https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify

Is there any way this package can be published pre-compiled, per the recommendation in the above link?

Thanks

**Comment by sindresorhus** [comment] 2018-03-15 20:06
Duplicate of #127

**Closed by sindresorhus** 2018-03-15 20:06 UTC
