### ISSUE TITLE
Can no longer import specific exports in TypeScript

### ISSUE THREAD

**Issue by veloek** [sindresorhus/query-string#364] opened 2022-12-14 12:48 UTC
Not sure if this was intentional, but it's no longer (with v8) possible to import specific exports in TypeScript, ex:
```
import { parse, stringify } from "query-string"
```

**Comment by MagicFame** [comment] 2022-12-14 16:09
Yes, you can import with the following line 
`import queryString from 'query-string';`

and use after 
`queryString.stringify()`

**Comment by sindresorhus** [comment] 2022-12-14 18:53
Duplicate of #363

**Closed by sindresorhus** 2022-12-14 18:53 UTC
