### ISSUE TITLE
param containing `+` replaces with ' ' (space)

### ISSUE THREAD

**Issue by abdullahtariq1171** [sindresorhus/query-string#133] opened 2018-03-19 17:10 UTC
When we parse `?email=someone+32@gmail.com`

It returns `{ email: 'someone 32@gmail.com' }`

Don't know if its expected behavior or a bug.

**Comment by sindresorhus** [comment] 2018-03-19 17:32
Duplicate of #119

**Closed by sindresorhus** 2018-03-19 17:32 UTC
