### ISSUE TITLE
Query string containing & breaks response object

### ISSUE THREAD

**Issue by pedrohma** [sindresorhus/query-string#367] opened 2023-02-27 21:22 UTC
I have the following url: https://localhost:3000/search?q=dave%20&%20busters

Inside my useEffect() method when trying to retrieve the parsed string, the response object doesn't seem to be accurate. Please check the screenshots below:

![image](https://user-images.githubusercontent.com/6583751/221688340-3a8a15b3-4a95-4f95-8ed6-a760091b58d3.png)
![image](https://user-images.githubusercontent.com/6583751/221688386-b69838c4-3637-4912-9f47-83877b627639.png)

**Comment by sindresorhus** [comment] 2023-02-28 05:06
Possibly duplicate of https://github.com/sindresorhus/query-string/issues/330

**Closed** 2024-06-01 13:25 UTC
