### ISSUE TITLE
2.0 in global namespace

### ISSUE THREAD

**Issue by niemyjski** [sindresorhus/query-string#21] opened 2015-05-05 20:43 UTC
I'm using v1 and just using it via the global namespace. is this still possible?

**Comment by arthurvr** [comment] 2015-05-05 20:46
No, we use commonjs right now as you can see in this commit: https://github.com/sindresorhus/query-string/commit/a4a45c12f76e4c727930f012e036319ae6c452cb. If you need browser support just use browserify.

**Comment by sindresorhus** [comment] 2015-05-05 20:47
Yes `$ a=$npm_package_name; browserify -r ./index:$a -s $a index.js -o browser.js` with browserify, or just stay on v1. The only change is to make it vanilla CommonJS.

Duplicate of #20.

**Comment by niemyjski** [comment] 2015-05-05 20:47
I don't use browserify or requirejs.. I need to keep my dependencies light.

On 5/5/15, Arthur Verschaeve <notifications@github.com> wrote:
> Closed #21.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/sindresorhus/query-string/issues/21#event-297629911


-- 
Thanks
-Blake Niemyjski

**Closed by arthurvr** 2015-05-05 20:46 UTC

**Comment by niemyjski** [comment] 2015-05-05 20:49
Could we look into using umd definition so you support amd/commonjs/browser
in 4 lines of code?

Thanks
-Blake Niemyjski

**Comment by kevva** [comment] 2015-05-05 20:49
Then use `1.x.x`.

**Comment by niemyjski** [comment] 2015-05-05 20:53
@sindresorhus thanks for your help, I wish this support umd: https://github.com/umdjs/umd would it be considered if someone did a pull request?

**Comment by kevva** [comment] 2015-05-05 20:58
Again, use `browserify` if you need to use in the browser https://github.com/sindresorhus/query-string/commit/a4a45c12f76e4c727930f012e036319ae6c452cb.

**Comment by sindresorhus** [comment] 2015-05-05 21:00
No. There's no good reason every module should include that junk. Just use browserify and you can use any module on npm without problem. Webpack is good too. Manually including UMD wrapped scripts in your HTML is the past. Use a builder.

**Comment by niemyjski** [comment] 2015-05-05 22:28
Your module is very generic and useful outside of node with no
dependencies. Hence I used it. It might be junk but it allows others
to use your library without extra work (amd/commonjs/global). Just
what I want to do add a new build task and more dependencies to
webpack/browserify a single dependency... when it would add .05kb to a
module. If you want to support the future you should be using es6
modules and not commonjs...

On 5/5/15, Sindre Sorhus <notifications@github.com> wrote:
> No. There's no good reason every module should include that junk. Just use
> browserify and you can use any module on npm without problem. Webpack is
> good too. Manually including UMD wrapped scripts in your HTML is the past.
> Use a builder.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/sindresorhus/query-string/issues/21#issuecomment-99220384


-- 
Thanks
-Blake Niemyjski

**Comment by sindresorhus** [comment] 2015-05-05 22:36
Bears repeating:

> Then use 1.x.x.

-

> Just
what I want to do add a new build task and more dependencies to
webpack/browserify a single dependency...

I'm not asking you to add a build chain just for this dependency. I'm saying your life would be a lot easier if you used a builder like browserify or webpack for all your dependencies. You would then not have to waste your time having this useless conversation and devs wouldn't have to add useless junk to their modules.

> If you want to support the future you should be using es6
modules and not commonjs...

For the foreseeable future those nice ES6 modules will still need to be transpiled down for older browsers using a build chain.

-

I'm not trying to be difficult here. I've just decided I'm done adding all this junk to all my modules when users are better off using something like browserify and webpack. You're of course free to whatever you want, but I'm not interested in supporting that.
