### ISSUE TITLE
doesn't work correctly when "+" character is presented

### ISSUE THREAD

**Issue by lebed2045** [sindresorhus/query-string#204] opened 2019-08-21 00:43 UTC
if you have a links with + inside (which is default behaviour `encodeURI(JSON.Stringify))` it doesn't parce correctly because of this https://github.com/SamVerschueren/decode-uri-component/issues/3
For example:
`a=5c=%257B%2522ecp%2522:%2522U2FsdGVkX189YRLMmgSS+lQjlhr9eR38t4KGRg1giASV1FC1`
will be parsed into `{"ecp":"U2FsdGVkX189YRLMmgSS lQjlhr9eR38t4KGRg1giASV1FC1}`

**Comment by sindresorhus** [comment] 2019-08-21 02:06
Duplicate of #119

**Closed by sindresorhus** 2019-08-21 02:06 UTC
