### ISSUE TITLE
Doesn't stringify objects

### ISSUE THREAD

**Issue by bashilbers** [sindresorhus/query-string#121] opened 2018-01-31 21:25 UTC
To me, `{ a: { b: 'c' } }` should be stringified to `?a[b]=c`. This tool puts `%5Bobject%20` in the query.. which is not what I want.

Maybe because there is no Object mapper? (arrays are being mapped like this: https://github.com/sindresorhus/query-string/blob/master/index.js#L192)

**Comment by sindresorhus** [comment] 2018-02-01 03:35
Duplicate of #100

**Closed by sindresorhus** 2018-02-01 03:35 UTC
