### ISSUE TITLE
query-string cannot minify because the code is not pre-compiled

### ISSUE THREAD

**Issue by stuartPounds** [sindresorhus/query-string#143] opened 2018-05-03 04:01 UTC
http://bit.ly/2tRViJ9
this is the hint URL I got from terminal. And it told to copy you code directly into my project. But I truely want the code is easier to use.

**Comment by sindresorhus** [comment] 2018-05-03 04:04
Duplicate of #137

**Closed by sindresorhus** 2018-05-03 04:04 UTC
