### ISSUE TITLE
6.0.0 fails to minify, 5.1.0 and 5.1.1 both do. 

### ISSUE THREAD

**Issue by wrossmorrow** [sindresorhus/query-string#136] opened 2018-03-23 21:16 UTC
I had a new app I tried to work with (using `query-string`) fail to build with either `npm run build` or `yarn build`. Error was 

```
Failed to minify the code from this file: 

 	./node_modules/query-string/index.js:8 

Read more here: http://bit.ly/2tRViJ9
```

I've had recent experience with `query-string`, and no such problems. Even re-building these "older" (~ 2 weeks) projects. I edited `package.json` to require `5.1.0` and `5.1.1` instead of `6.0.0` and had no such problems; build succeeded. 

Mac OSX, `yarn` 1.5.1, `npm` 5.6.0, `node` 9.4.0. Basic settings from `create-react-app`.

**Comment by sindresorhus** [comment] 2018-03-23 21:18
Version 6 is a major release. Please read the release notes.

**Comment by sindresorhus** [comment] 2018-03-23 21:19
Duplicate of #126

**Closed by sindresorhus** 2018-03-23 21:19 UTC
