### ISSUE TITLE
extract method does not work with '#' since v6.5

### ISSUE THREAD

**Issue by albert-gonzalez** [sindresorhus/query-string#225] opened 2019-11-27 10:18 UTC
Hi!

I am trying to update the library from v6.2 and I have found an issue since v6.5. The extract method returns an empty string when I pass a value with a #. For example

- `extract('https://wwww.domain.com#hello?param=1');` // returns ''
- `extract('#hello?param=1');` // returns '';

I think the problem is in the function "removeHash", introduced in the v6.5. This function removes all the string that is after the #. I wrote this simple fiddle with an example: https://jsfiddle.net/5Ljnwc07/

Do you think it's a bug? Or I am doing something wrong?

Thank you!

**Comment by sindresorhus** [comment] 2019-11-27 10:25
// @ChrisCindy

**Comment by serhii12** [comment] 2020-01-31 20:44
Any updates on this?

**Comment by samuelpetroline** [comment] 2020-02-03 20:36
It seems that this is the intended behaviour:

https://github.com/sindresorhus/query-string/blob/a1d108fe41ac34ca574d5e00823d0e4562c9d8be/test/extract.js#L8

**Comment by baile320** [comment] 2020-02-21 00:22
Additional potential support that this is intended behavior: see this [stackoverflow answer](https://stackoverflow.com/questions/12682952/proper-url-forming-with-query-string-and-anchor-hashtag)(which references to [RFC 3986](https://tools.ietf.org/html/rfc3986#section-3)). Percent encoding can escape the #, if that is something you have control over.

**Comment by sindresorhus** [comment] 2020-04-12 14:56
Closing as this is working as intended.

**Closed by sindresorhus** 2020-04-12 14:56 UTC
Labels: bug, help wanted
