### ISSUE TITLE
Failed to minify the code from this file

### ISSUE THREAD

**Issue by nWidart** [sindresorhus/query-string#137] opened 2018-03-27 07:12 UTC
Hello,

After including your package I'm unable to build the project. It's showing this error:

```
Failed to minify the code from this file: 

        ./node_modules/query-string/index.js:8 

```

With a link to this: https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify

**Comment by sindresorhus** [comment] 2018-03-27 07:26
Duplicate of #126

**Closed by sindresorhus** 2018-03-27 07:26 UTC
