### ISSUE TITLE
distribution code should be compiled into ES5

### ISSUE THREAD

**Issue by vukasin-nikodijevic** [sindresorhus/query-string#135] opened 2018-03-23 14:08 UTC
I have problem to minify my code during build process as dependency `query-string
` file has ES6 syntax contained into index.js 

#### Error
```
Failed to compile.
Failed to minify the code from this file: 
 ./node_modules/query-string/index.js:8 
```

#### More on issue:
https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify

**Comment by SamVerschueren** [comment] 2018-03-23 15:11
Duplicate of #126, #127, #129, #132. See https://github.com/sindresorhus/query-string/releases/tag/v6.0.0

**Closed by SamVerschueren** 2018-03-23 15:11 UTC

**Comment by emadow** [comment] 2018-03-23 17:01
Seems to be broken in 6.0.0 too :(

**Comment by SamVerschueren** [comment] 2018-03-23 17:32
If you want support for Webpack, use v5 instead of v6.

**Comment by emadow** [comment] 2018-03-23 17:51
v5:
```
    Invalid assignment [./~/source-map-loader!./~/query-string/index.js:8,0][vendor-d8b76d57.js:38266,30]
```

**Comment by emadow** [comment] 2018-03-23 17:58
Seems like this was an issue with the `@types/query-string` package for TS support. I was able to get around this.

Thanks for your work on this library!
