### ISSUE TITLE
ES5 Bundle

### ISSUE THREAD

**Issue by lcharbon** [sindresorhus/query-string#208] opened 2019-09-06 12:04 UTC
When building with Webpack this package is not down compiled and does not work on internet explorer without a good deal of configuration. qs.js has a dist file that holds a down compiled build. Can this be added to query-string?

**Comment by sindresorhus** [comment] 2019-09-06 12:52
Duplicate of #135

**Comment by sindresorhus** [comment] 2019-09-06 12:52
Check out [`babel-engine-plugin`](https://github.com/SamVerschueren/babel-engine-plugin), which transpiles only the dependencies that needs to be transpiled.

If you use Create React App, upgrade to [Create React App v2](https://reactjs.org/blog/2018/10/01/create-react-app-v2.html). It supports automatic transpilation of dependencies, which will make this package *just work*.

**Closed by sindresorhus** 2019-09-06 12:52 UTC

**Comment by peteruithoven** [comment] 2020-08-11 09:48
For people using Vue and the Vue cli you can use the `transpileDependencies` option in vue.config.js:
https://cli.vuejs.org/config/#transpiledependencies
To get query-string working in IE 11 I also needed to add `strict-uri-encode` and `split-on-first`:
```
// vue.config.js
module.exports = {
  transpileDependencies: [
    "query-string",
    "strict-uri-encode",
    "split-on-first"
  ]
}
```

The alternative, like mentioned in the readme, is using version 5.
