### ISSUE TITLE
Does stringify support associative arrays ?

### ISSUE THREAD

**Issue by ErikParso** [sindresorhus/query-string#251] opened 2020-03-06 10:53 UTC
Hello. I see there is a posibility specify array format so stringify result can look like this

'foo[0]=1&foo[1]=2&foo[2]=3'

Is it possible to stringify also associative arrays. I need to build a url with search params looking like this.. 

'foo[carId]=1&foo[dealerId]=2&foo[anotherKey]=3'

Problem is, the parenthesis in key are normalized if i specify my object like this..

{
   "foo[carId]" : 1,
   "foo[dealerId]" : 2,
   "foo[anotherKey]" : 3 
}

Another approach with arrayFormat: 'index' option set is not working neither

{
   "foo" : {
        carId: 1,
        dealerId: 2,
        anotherKey: 3
    } as { [index: string]: string }
}

**Comment by sindresorhus** [comment] 2020-03-06 11:17
Duplicate of #250

**Closed by sindresorhus** 2020-03-06 11:17 UTC
